content = (
    'import { useState, useEffect } from "react";\n'
    '\n'
    'export default function BeforeAfterToggle() {\n'
    '  const [enabled, setEnabled] = useState(true);\n'
    '  const [busy, setBusy] = useState(false);\n'
    '  const apiKey = import.meta.env.VITE_PROXY_API_KEY || "test-key-123";\n'
    '\n'
    '  useEffect(() => {\n'
    '    fetch("http://localhost:8000/aegis_status")\n'
    '      .then(r => r.json())\n'
    '      .then(d => setEnabled(d.aegis_enabled ?? true))\n'
    '      .catch(() => {});\n'
    '  }, []);\n'
    '\n'
    '  async function toggle() {\n'
    '    setBusy(true);\n'
    '    try {\n'
    '      const resp = await fetch("http://localhost:8000/aegis_mode", {\n'
    '        method: "POST",\n'
    '        headers: { "Content-Type": "application/json", "X-API-Key": apiKey },\n'
    '        body: JSON.stringify({ enabled: !enabled }),\n'
    '      });\n'
    '      if (resp.ok) setEnabled((await resp.json()).aegis_enabled);\n'
    '    } catch {} finally { setBusy(false); }\n'
    '  }\n'
    '\n'
    '  return (\n'
    '    <div style={{display:"flex",alignItems:"center",gap:8}}>\n'
    '      <span style={{fontSize:12,opacity:0.6}}>Aegis</span>\n'
    '      <button\n'
    '        onClick={toggle} disabled={busy}\n'
    '        title={enabled ? "Disable Aegis" : "Enable Aegis"}\n'
    '        style={{\n'
    '          position:"relative",width:40,height:20,borderRadius:10,border:"none",\n'
    '          cursor:"pointer",opacity:busy?0.5:1,transition:"background 0.2s",\n'
    '          background:enabled?"#3fb950":"#f85149"\n'
    '        }}\n'
    '      >\n'
    '        <span style={{\n'
    '          position:"absolute",top:2,left:enabled?20:2,\n'
    '          width:16,height:16,borderRadius:"50%",background:"white",\n'
    '          transition:"left 0.2s",display:"block"\n'
    '        }}/>\n'
    '      </button>\n'
    '      <span style={{fontSize:12,fontWeight:600,color:enabled?"#3fb950":"#f85149"}}>\n'
    '        {enabled ? "ON" : "OFF"}\n'
    '      </span>\n'
    '    </div>\n'
    '  );\n'
    '}\n'
)
with open(r"dashboard/src/components/BeforeAfterToggle.jsx", "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print("OK")
